### Get all books
GET http://localhost:8080/books
Accept: application/json

###

### Create a new book
POST http://localhost:8080/books
Content-Type: application/json

{
  "title": "1984",
  "author": "George Orwell"
}

###

### Update a book
PUT http://localhost:8080/books/1
Content-Type: application/json

{
  "title": "Brave New World",
  "author": "Aldous Huxley"
}

###

### Delete a book
DELETE http://localhost:8080/books/1

###

### Get all books again to verify changes
GET http://localhost:8080/books
Accept: application/json


